name: external_dependencies
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  flutter_modular: 3.4.1+1
  flutter_triple: 1.2.7+4
  mobx_triple: 1.1.3+1
  firebase_auth: 3.4.2
  firebase_core: 1.21.1
  cloud_firestore: 3.3.0
  dartz: 0.10.1
  local_auth: 2.1.2
  shared_preferences: 2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.external_dependencies
    iosBundleIdentifier: com.example.externalDependencies
