name: base_app
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:

  external_dependencies:
    path: '../external_dependencies'

  commons:
    path: '../commons'

  auth:
    path: '../auth'

  safe_zone:
    path: '../safe_zone'

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.base_app
    iosBundleIdentifier: com.example.baseApp
